### ISSUE TITLE
Typo in README example

### ISSUE THREAD

**Issue by mdiin** [magnus-madsen/umonitor#1]
A small typo in the README:

> An action is attached to a transition with the `@@` operator, like so:

```
when Online {
    Dn(self) -> Online @@ notify-offline
}
```

> Thus, when a `Dn` event is received in the `Online` state, 
> a transition is made to the `Offline` state and the `notify-offline` action is executed.

`Dn(self) -> Online @@ notify-offline` should be `Dn(self) -> Offline @@ notify-offline` I think.

**Comment by magnus-madsen** [comment]
Fixed.
